### ISSUE TITLE
Move hostname to last argument on windows

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/pingman#21]
As per PR #12 and PR #20 , we moved the hostname to the last argument on the ping command on unix systems.

I propose we do the same for Windows as well so we can maintain a uniform standard across platforms.

All we need to do is follow the steps as in #12 or #20 .

- Move `ip` to last argument in src/builder/windows.ts
- Adjust the tests in test/builder/builder.ts

I'll take this up once I get the time. Anyone who wants to work on this on the meantime, can comment here if you want a more detailed idea about what we're trying to achieve.

**Comment by sravanth-chebrolu** [comment]
Hi, I'd like to take this up!

**Comment by sravanth-chebrolu** [comment]
I've observed that on Windows there are separate function calls to check for IPV6/4, should I be worrying about that?

**Comment by dopecodez** [comment]
@sravanth-chebrolu all yours, thanks 😄
