### ISSUE TITLE
Throws IP_NOT_VALID error on short subdomains

### ISSUE THREAD

**Issue by foxxyz** [dopecodez/pingman#33]
When using short subdomains (E.G. `i.test.example.com`), calling `ping` will incorrectly throw an error with `Given IP address is not valid`.

Likely due to a too-strict regex in [`validateIp`](https://github.com/dopecodez/pingman/blob/master/src/helper.ts#L12).

Example:
```
try {
    await ping('i.test.example.com') // will throw "ipError: Given IP address is not valid"
}
catch(err) {
    console.error(err)
}
```

**Comment by dopecodez** [comment]
Released on https://github.com/dopecodez/pingman/releases/tag/v1.1.3 🎉 .
