### ISSUE TITLE
can not work with browserify 

### ISSUE THREAD

**Issue by LQYcode** [dopecodez/pingman#37]
This is my demo code from this  repo
`
const pingman = require('pingman');

(async () => {
	try {
		const response = await pingman('127.0.0.1');
		console.log(response);
		if(response.alive){
		//=>if pinged ip is available and responds
		}	
	} catch (error) {
		console.log(error);
		//=> 'Internal server error ...'
	}
})();
`

when i run  " browserify  index.js > bundle.js",
the error is as shown :
Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat 'D:\codes\net_stat\process'
    required by D:\codes\net_stat\node_modules\pingman\dist\src\builder\windows.js.

please.
thanks in advance.

**Comment by dopecodez** [comment]
#10 

Have you tried the solutions listed here? This issue might be able to help you.

**Comment by dopecodez** [comment]
@LQYcode Closing this as stale and multiple issues related to browserify and electron have already been reported.
