### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/pingman#9]
We currently have 99% test coverage which isn't bad, but could be better.

All tests are run with `ava` which enables concurrent execution.
The files currently missing a test are `ping.ts` and `index.ts`, which need to be mocked in order to test without having any over the network calls.

Other than this, even other tests or patterns are welcome. First-timers are welcome to give unit testing a try and we can discuss ideas if you have any.

**Comment by binkpitch** [comment]
Can I take this issue?

**Comment by dopecodez** [comment]
Sure @binkpitch , tell me if you need any help with your contribution.

**Comment by binkpitch** [comment]
May I ask what script you used to see the code coverage?

**Comment by dopecodez** [comment]
We use `travis` to trigger a test report at `codeclimate`. You should be able to see the code coverage as soon as you open a PR against master.

**Comment by dopecodez** [comment]
For anyone looking at this issue runnning `npm test` will trigger `nyc` and you can see the file by file coverage on your local as per the latest updated `package.json`

**Comment by sreesh-mallya** [comment]
Hey, anyone still working on this?

**Comment by dopecodez** [comment]
Closing issue as test coverage is 99% right now, thanks to everyone who helped improve the same 😄
